In [1]:
# Load NumPy package
import numpy as np

In [3]:
# Create array
array1 = np.array([['a', 'a'], ['b', 'b'], ['c', 'c']])

In [4]:
# Insert 'z's in row 3
np.insert(array1, 3, 'z', axis=0)

array([['a', 'a'],
       ['b', 'b'],
       ['c', 'c'],
       ['z', 'z']], dtype='<U1')

In [5]:
# Insert 0s in column 1
np.insert(array1, 1, '0', axis=1)

array([['a', '0', 'a'],
       ['b', '0', 'b'],
       ['c', '0', 'c']], dtype='<U1')

In [6]:
# Delete row 1
np.delete(array1, 1, axis=0)

array([['a', 'a'],
       ['c', 'c']], dtype='<U1')

In [7]:
# Return array with 3 zeros
np.zeros(3)

array([0., 0., 0.])

In [8]:
# Create another array
array2 = np.array(['z', 'b', 'a', 'd', 'c'])

In [9]:
# Display the other array
array2

array(['z', 'b', 'a', 'd', 'c'], dtype='<U1')

In [10]:
# Sort array2
np.sort(array2, None)

array(['a', 'b', 'c', 'd', 'z'], dtype='<U1')

In [11]:
# Delete array element with index 1
np.delete(array2, 1)

array(['z', 'a', 'd', 'c'], dtype='<U1')

In [12]:
array3 = np.array([[3, 2], [5, 6], [4, 2]])
array3

array([[3, 2],
       [5, 6],
       [4, 2]])

In [13]:
# Sort along axis=0
np.sort(array3, axis=0)

array([[3, 2],
       [4, 2],
       [5, 6]])

In [14]:
# Sort along axis=1
np.sort(array3, axis=1)

array([[2, 3],
       [5, 6],
       [2, 4]])